version: '3'
services:
  nginx:
    container_name: nginx
    image: nginx:1.13
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
angular:
  container_name : angular
  build: ./frontend/usersapp
  restart: always
  ports:
    - 4200:4200
  depends_on:
    - app
mysql:
  container_name: mysql
  image: mysql/mysql-server:5.7
  environment:
    MYSQL_DATABASE: usersdb
    MYSQL_ROOT_PASSWORD: FSPWcris*24_92
    MYSQL_ROOT_HOST: '%'
  ports:
  - "3306:3306"
  restart: always
springboot:
  restart : always
  build:
    context: ./backend/test
    dockerfile: Dockerfile
  working_dir: /springboot
  volumes:
    - ./springboot:/springboot
    - ~/.m2:/root/.m2
  expose:
    - "8081"
  depends_on:
    - nginx
    - mysql
  command: mvn clean spring-boot:run -Dspring-boot.run.profiles=docker